---
# handlers file for prometheus
- name: Start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: true

- name: Start alertmanager
  systemd:
    name: alertmanager
    state: started
    enabled: yes
    daemon_reload: true

- name: Start node_explorer
  systemd:
    name: node_explorer
    state: started
    enabled: yes
    daemon_reload: true